apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      run: back
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: back
    spec:
      containers:
      - image: eu.gcr.io/blockchain-js/back:VERSION
        imagePullPolicy: IfNotPresent
        name: back
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}